/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.35
 * Generated at: 2013-10-05 01:14:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.LoginModel;

public final class panel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("Nombre:panel.jsp\r\n");
      out.write("Descripcion:Pagina Principal\r\n");
      out.write("Autores:Yoshitomi Maehara/Liliana Gonzales\r\n");
      out.write("Email:\r\n");
      out.write("-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css\\styles.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css\\bootstrap.min.css\">\r\n");
      out.write("<script src=\"js\\jquery.js\"></script>\r\n");
      out.write("<script src=\"js\\scripts.js\"></script>\r\n");
      out.write("<script src=\"js\\bootstrap.js\"></script>\r\n");
      out.write("<title>.::::Sistema de Evaluaciones Academicas::::. - Principal</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"cabecera_panel\">\r\n");
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div> \r\n");
      out.write("\t<nav class=\"menu_panel navbar\">\r\n");
      out.write("\t<div class=\"navbar-inner\">\r\n");
      out.write("\t<a class=\"brand\" href=\"panel.jsp\"> Principal </a>\r\n");
      out.write("    \t<div class=\"container\">\r\n");
      out.write("\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t \t<li class=\"dropdown\">\r\n");
      out.write("    \t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\"> Academico <b class=\"caret\"></b></a>\r\n");
      out.write("    \t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"accesos\">Cursos</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\" class=\"accesos\">Estadisticas</a>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t\t</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"  class=\"accesos\">Perfil</a></li>\r\n");
      out.write("  \t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("  \t\t\t\t<a class=\"dropdown-toggle\" data-toggle=\"dropdown\">Mantenimiento<b class=\"caret\"></b></a>\r\n");
      out.write("  \t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"alumno.jsp\" class=\"accesos\">Alumnos</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"profesor.jsp\" class=\"accesos\">Profesores</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"curso.jsp\" class=\"accesos\">Cursos</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"usuario.jsp\" class=\"accesos\">Usuarios</a></li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("  \t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"nav pull-right\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><i class=\"icon-off\"></i> Cerrar Sesion</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<section class=\"contenido_panel\">\r\n");
      out.write("\t\t<article id=\"main\" class=\"contenedor hero-unit\">\r\n");
      out.write("\t\t\t<h1>Bienvenido </h1>\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
